data:
    dataset: "CELEBA_HQ"
    category: "CELEBA_HQ"
    image_size: 256
    channels: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 20
    data_root: "/home/catalin/Desktop/Disertatie/Datasets/celeba_hq_lmdb"

model:
    type: "vgg"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
    projector:
        t_edit: 400

training:
    batch_size: 6 # 1 # 6
    n_epochs: 50 #10000
    n_iters: 5000000
    snapshot_freq: 5000 # 30000 # 5000
    validation_freq: 20000 # 30000 # 20000

sampling:
    batch_size: 16 # 16
    last_only: True
    # ckpt_id: 810000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
    grad_clip: 1.0
